# Inlcude _pages
include: ["_pages"]

# No dates in URL's
permalink: /:title/

# Where all of your source
# pug/HTML/includes/layouts
# will be
source: src

# Where your compiled
# files will output to.
# default is site you can change it like this:
# destination: dist

# Enabling the livereload
# plugin by default.
livereload: true

# Setting our sass
# directory.
sass:
    sass_dir: assets/css

# use modern JS and minification
plugins:
  - jekyll-babel
  - jekyll-autoprefixer
