# Inlcude _pages
include: ["_pages"]

# Exclude _webpack fro jekyll watching
exclude: ["_webpack"]

# No dates in URL's
permalink: /:title/

# Where all of your Markup and HTML files are. (Assets like JS and SCSS are handeled by Webpack)
source: src

# Where your compiled files will be outputted to.
destination: dist

# use Jekyll autoprefixer
plugins:
  - jekyll-autoprefixer
  - jekyll-last-modified-at
  - jekyll-sitemap

# Default variables, you can overwrite them in posts or pages frontmatter
title: The Page Title
short_name: Page Title
ogimage: urltosuperfancyimage.jpg
description: The page description
background_color: "#fff"
theme_color: "#536878"

# Editor config options for Cloudcannon
_options:
  content:
    styles: src/assets/wysiwyg.css
    bold: true
    italic: true
    link: true
    numeredlist: true
    bulletlist: true
