# Inlcude _pages
include: ["_pages"]

# No dates in URL's
permalink: /:title/

# Where all of your source
# pug/HTML/includes/layouts
# will be
source: src

# Where your compiled
# files will output to.
destination: dist

# Setting our sass
# directory.
sass:
    sass_dir: assets/css
    style: compressed
# use modern JS and minification
plugins:
  - jekyll-babel
  - jekyll-autoprefixer
